export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_ERROR = "FETCH_PRODUCTS_ERROR";
export const PUT_FOUND_PRODUCTS = "PUT_FOUND_PRODUCTS";
export const PUT_CURRENT_POSTS_FOR_PAGINATION="PUT_CURRENT_POSTS_FOR_PAGINATION";

